import type { DesignItem } from "@/types/product";

export const PRODUCTS = [
  {
    id: "test-murah",
    label: "Test Murah (Rp 1.000)",
    file: "/products/shirt.png",
    overlayFile: undefined,
    isGiftCard: false,
    textArea: undefined,
    price: 1000,
    weight: 100,
    sizeChart: {
      regular: [{ size: "ALL", length: 1, chest: 1, waist: 1 }],
      kids: [],
    },
    colors: [{ name: "White", hex: "#FFFFFF", file: "/products/shirt.png" }],
    category: "test",
  },
  {
    id: "fajamas",
    label: "T-Shirt",
    file: "/products/shirt.png",
    overlayFile: undefined,
    isGiftCard: false,
    textArea: undefined,
    price: 308000,
    weight: 240,
    sizeChart: {
      regular: [
        { size: "XS", length: 61, chest: 46, waist: 46 },
        { size: "S", length: 65, chest: 49, waist: 49 },
        { size: "M", length: 69.5, chest: 52, waist: 52 },
        { size: "L", length: 73, chest: 55, waist: 55 },
        { size: "XL", length: 77, chest: 58, waist: 58 },
        { size: "XXL", length: 81, chest: 61, waist: 61 },
        { size: "3XL", length: 82, chest: 67, waist: 67 },
        { size: "4XL", length: 83, chest: 73, waist: 73 },
        { size: "5XL", length: 84, chest: 76, waist: 76 },
      ],
      kids: [
        { size: "0-1Y", length: 32, chest: 31, waist: 31 },
        { size: "1-2Y", length: 38, chest: 34, waist: 34 },
        { size: "3-4Y", length: 44, chest: 37, waist: 37 },
        { size: "5-6Y", length: 50, chest: 40, waist: 40 },
        { size: "7-8Y", length: 56, chest: 43, waist: 43 },
      ],
    },
  },
  {
    id: "socks",
    label: "Socks",
    file: "/products/socks.png",
    overlayFile: undefined,
    isGiftCard: false,
    textArea: undefined,
    price: 159000,
    weight: 98,
  },
  {
    id: "totebag",
    label: "Tote Bag",
    file: "/products/totebag-full.png",
    overlayFile: "/products/totebag-handles.png",
    isGiftCard: false,
    textArea: undefined,
    price: 98000,
    weight: 167,
  },
  {
    id: "polo",
    label: "Polo Shirt",
    file: "/products/polo.png",
    overlayFile: undefined,
    isGiftCard: false,
    textArea: undefined,
    price: 328000,
    weight: 260,
    sizeChart: {
      regular: [
        { size: "S", length: 66, chest: 50, waist: 50 },
        { size: "M", length: 70, chest: 53, waist: 53 },
        { size: "L", length: 74, chest: 56, waist: 56 },
        { size: "XL", length: 78, chest: 59, waist: 59 },
      ],
      kids: [],
    },
  },
  {
    id: "short",
    label: "Short Pants",
    file: "/products/short.png",
    overlayFile: undefined,
    isGiftCard: false,
    textArea: undefined,
    price: 250000,
    weight: 180,
    sizeChart: {
      regular: [
        { size: "S", length: 42, chest: 30, waist: 30 },
        { size: "M", length: 44, chest: 32, waist: 32 },
        { size: "L", length: 46, chest: 34, waist: 34 },
        { size: "XL", length: 48, chest: 36, waist: 36 },
      ],
      kids: [],
    },
  },
];

export const GIFT_CARD_TEMPLATES = [
  {
    id: "gift-card-birthday",
    name: "Birthday",
    file: "/products/giftcard/birthday.webp",
    textArea: { x: 181, y: 56, w: 819, h: 1021 },
  },
  {
    id: "gift-card-family",
    name: "Family",
    file: "/products/giftcard/family.webp",
    textArea: { x: 128, y: 102, w: 808, h: 1072 },
  },
  {
    id: "gift-card-friends",
    name: "Friends",
    file: "/products/giftcard/friends.webp",
    textArea: { x: 181, y: 56, w: 819, h: 1021 },
  },
  {
    id: "gift-card-happified",
    name: "Happified",
    file: "/products/giftcard/happified.webp",
    textArea: { x: 128, y: 102, w: 808, h: 1072 },
  },
  {
    id: "gift-card-lovers",
    name: "Lovers",
    file: "/products/giftcard/lovers.webp",
    textArea: { x: 181, y: 56, w: 819, h: 1021 },
  },
];

export const PREDEFINED_DESIGNS: DesignItem[] = [
  { id: "8Ball", name: "8 Ball", src: "/mockup/8Ball.png" },
  { id: "Acoustic1", name: "Acoustic 1", src: "/mockup/Acoustic-1.png" },
  {
    id: "AppleFanboy1",
    name: "Apple Fanboy 1",
    src: "/mockup/Apple-Fanboy-1.png",
  },
  { id: "Basketball", name: "Basketball", src: "/mockup/Basketball.png" },
  { id: "BestBf", name: "Best BF", src: "/mockup/Best-Bf.png" },
  { id: "BestDad", name: "Best Dad", src: "/mockup/Best-Dad.png" },
  {
    id: "BestDaughter",
    name: "Best Daughter",
    src: "/mockup/Best-Daughter.png",
  },
  { id: "BestGf", name: "Best GF", src: "/mockup/Best-Gf.png" },
  { id: "BestHusband", name: "Best Husband", src: "/mockup/Best-Husband.png" },
  { id: "BestMom", name: "Best Mom", src: "/mockup/Best-Mom.png" },
  { id: "BestSon", name: "Best Son", src: "/mockup/Best-Son.png" },
  { id: "BestWife", name: "Best Wife", src: "/mockup/Best-Wife.png" },
  { id: "BFF", name: "BFF", src: "/mockup/BFF.png" },
  {
    id: "BiskuitLebaran1",
    name: "Biskuit Lebaran 1",
    src: "/mockup/Biskuit-Lebaran-1.png",
  },
  { id: "Boba1", name: "Boba 1", src: "/mockup/Boba-1.png" },
  { id: "Burger", name: "Burger", src: "/mockup/Burger.png" },
  { id: "Cheese1", name: "Cheese 1", src: "/mockup/Cheese-1.png" },
  {
    id: "ChickenGoreng1",
    name: "Chicken Goreng 1",
    src: "/mockup/Chicken-Goreng-1.png",
  },
  { id: "Cinnamon1", name: "Cinnamon 1", src: "/mockup/Cinnamon-1.png" },
  {
    id: "CoffeeAddict",
    name: "Coffee Addict",
    src: "/mockup/Coffee-Addict.png",
  },
  {
    id: "CongratsHappyBirthday",
    name: "Congrats Happy Birthday",
    src: "/mockup/Congrats-HappyBirthday.png",
  },
  {
    id: "CustomTextBlack",
    name: "Custom Text Black",
    src: "/mockup/Custom-Text-Black.png",
  },
  {
    id: "CustomTextWhite",
    name: "Custom Text White",
    src: "/mockup/Custom-Text-White.png",
  },
  {
    id: "DonutDisturbMe",
    name: "Donut Disturb Me",
    src: "/mockup/Donut-Disturb-me.png",
  },
  { id: "Electric", name: "Electric", src: "/mockup/Electric.png" },
  { id: "Fries1", name: "Fries 1", src: "/mockup/Fries-1.png" },
  {
    id: "HoleinOneGolf",
    name: "Hole in One Golf",
    src: "/mockup/HoleinOne-Golf.png",
  },
  { id: "IceCoffee1", name: "Ice Coffee 1", src: "/mockup/IceCoffee-1.png" },
  { id: "InstantMe1", name: "Instant Me 1", src: "/mockup/Instant-me-1.png" },
  { id: "Juara1", name: "Juara 1", src: "/mockup/Juara-1.png" },
  { id: "JuaraSatu", name: "Juara Satu", src: "/mockup/Juara-Satu.png" },
  {
    id: "KerupukBahagia",
    name: "Kerupuk Bahagia",
    src: "/mockup/Kerupuk-Bahagia.png",
  },
  {
    id: "KerupukLanggeng",
    name: "Kerupuk Langgeng",
    src: "/mockup/Kerupuk-Langgeng.png",
  },
  {
    id: "KerupukSentosa",
    name: "Kerupuk Sentosa",
    src: "/mockup/Kerupuk-Sentosa.png",
  },
  { id: "Kurma1", name: "Kurma 1", src: "/mockup/Kurma-1.png" },
  { id: "MakeUp", name: "Make Up", src: "/mockup/MakeUp.png" },
  {
    id: "MangkokAyam1",
    name: "Mangkok Ayam 1",
    src: "/mockup/Mangkok-Ayam-1.png",
  },
  { id: "Martabak1", name: "Martabak 1", src: "/mockup/Martabak-1.png" },
  { id: "NasiGoreng", name: "Nasi Goreng", src: "/mockup/Nasi-Goreng.png" },
  {
    id: "NasiPadang1",
    name: "Nasi Padang 1",
    src: "/mockup/Nasi-Padang-1.png",
  },
  { id: "Pete", name: "Pete", src: "/mockup/Pete.png" },
  { id: "Pizza1", name: "Pizza 1", src: "/mockup/Pizza-1.png" },
  {
    id: "ProVideoGame",
    name: "Pro Video Game",
    src: "/mockup/ProVideoGame.png",
  },
  { id: "SatuSate1", name: "Satu Sate 1", src: "/mockup/Satu-Sate-1.png" },
  { id: "Soccer1", name: "Soccer 1", src: "/mockup/Soccer-1.png" },
  { id: "SpicyCabe", name: "Spicy Cabe", src: "/mockup/SpicyCabe.png" },
  { id: "SunnySide", name: "Sunny Side", src: "/mockup/SunnySide.png" },
  { id: "SushiSama", name: "Sushi Sama", src: "/mockup/Sushi-Sama.png" },
  { id: "Tempe1", name: "Tempe 1", src: "/mockup/Tempe-1.png" },
  { id: "Tennis1", name: "Tennis 1", src: "/mockup/Tennis-1.png" },
  { id: "Vespa", name: "Vespa", src: "/mockup/Vespa-.png" },
  { id: "Vinyl", name: "Vinyl", src: "/mockup/Vinyl.png" },
  { id: "Wine1", name: "Wine 1", src: "/mockup/Wine-1.png" },
  {
    id: "WordsFromHeart",
    name: "Words From Heart",
    src: "/mockup/Words-From-Heart.png",
  },
  {
    id: "YouJustGotALetter1",
    name: "You Just Got a Letter 1",
    src: "/mockup/You-Just-Got-a-Letter-1.png",
  },
  {
    id: "YouJustGotALetter2",
    name: "You Just Got a Letter 2",
    src: "/mockup/You-Just-Got-a-Letter-2.png",
  },
];

export const DESIGN_PAIRS: Record<string, string> = {
  "/mockup/Acoustic-1.png": "/mockup/Acoustic-2.png",
  "/mockup/Biskuit-Lebaran-1.png": "/mockup/Biskuit-Lebaran-2.png",
  "/mockup/Boba-1.png": "/mockup/Boba-2.png",
  "/mockup/Cheese-1.png": "/mockup/Cheese-2.png",
  "/mockup/Chicken-Goreng-1.png": "/mockup/Chicken-Goreng-2.png",
  "/mockup/Cinnamon-1.png": "/mockup/Cinnamon-2.png",
  "/mockup/Fries-1.png": "/mockup/Fries-2.png",
  "/mockup/IceCoffee-1.png": "/mockup/IceCoffee-2.png",
  "/mockup/Instant-me-1.png": "/mockup/Instant-me-2.png",
  "/mockup/Kurma-1.png": "/mockup/Kurma-2.png",
  "/mockup/Mangkok-Ayam-1.png": "/mockup/Mangkok-Ayam-2.png",
  "/mockup/Martabak-1.png": "/mockup/Martabak-2.png",
  "/mockup/Nasi-Padang-1.png": "/mockup/Nasi-Padang-2.png",
  "/mockup/Pizza-1.png": "/mockup/Pizza-2.png",
  "/mockup/Satu-Sate-1.png": "/mockup/Satu-Sate-2.png",
  "/mockup/Soccer-1.png": "/mockup/Soccer-2.png",
  "/mockup/Tempe-1.png": "/mockup/Tempe-2.png",
  "/mockup/Tennis-1.png": "/mockup/Tennis-2.png",
  "/mockup/Wine-1.png": "/mockup/Wine-2.png",
  "/mockup/You-Just-Got-a-Letter-1.png": "/mockup/You-Just-Got-a-Letter-2.png",
};

export const SHIRT_COLORS = [
  { name: "Snow White", hex: "#ffffff" },
  { name: "Lollipop Purple", hex: "#935e9e" },
  { name: "Lovestruck Pink", hex: "#e596df" },
  { name: "Fresh Salmon", hex: "#e98480" },
  { name: "Emerald Green", hex: "#73d1ae" },
  { name: "Starlight Yellow", hex: "#f8ca3f" },
  { name: "Joy Blue", hex: "#78b3db" },
  { name: "Candy Red", hex: "#d14f53" },
  { name: "Deep Blue", hex: "#3d44ac" },
  { name: "Sky Blue", hex: "#cdebf0" },
  { name: "Caffeinated Brown", hex: "#bf6430" },
  { name: "Teal", hex: "#008080" },
  { name: "Lilac", hex: "#d8b9ff" },
  { name: "Turquoise", hex: "#33bdb7" },
  { name: "Lime", hex: "#88c540" },
  { name: "Fuchsia Pink", hex: "#e23a95" },
  { name: "Pumpkin Spice", hex: "#ff5e0e" },
  { name: "Navy", hex: "#0d1139" },
  { name: "Gold", hex: "#ffa300" },
  { name: "Origin Green", hex: "#36845b" },
  { name: "Cupcake", hex: "#fabccb" },
  { name: "Light Violet", hex: "#bd93dd" },
  { name: "Playful Blue", hex: "#5f9dd1" },
  { name: "Jet Black", hex: "#030303" },
  { name: "Rose", hex: "#a41040" },
  { name: "Khaki", hex: "#a09076" },
  { name: "Pebble Grey", hex: "#adb5c1" },
  { name: "Dark Chocolate", hex: "#473728" },
  { name: "Sandy Pink", hex: "#f6dbd4" },
  { name: "Lemon", hex: "#fdf785" },
];
